services:
  - type: web
    name: hoshi-constellation-app
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build:web
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html